# Generated by Django 4.0 on 2022-01-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
